{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "prometheus-mcp-server.fullname" . }}
  labels:
    {{- include "prometheus-mcp-server.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.serviceMonitor.namespace }}
  namespace: {{ . }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "prometheus-mcp-server.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      {{- with .Values.serviceMonitor.interval }}
      interval: {{ . }}
      {{- end }}
      {{- with .Values.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ . }}
      {{- end }}
      path: /
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}
